spring:
  application:
    name: ms-cadastro
# Configuração do DEVTOOLS
  devtools:
    restart:
      enabled: true
# Configurações do banco de dados MySQL
  datasource:
    url: jdbc:mysql://wfsweb.com:3306/springdb
    username: root
    password: kyE5bl_-KHqC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maxLifetime: 600000

# Configuração do JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


keycloak:
  realm: sige
  auth-server-url: http://wfsweb.com:8080
  ssl-required: external
  resource: backend
  use-resource-role-mappings: true
  bearer-only: true
  public-client: true

server:
  port:
    8081